Repository 100-hours-a-week/11-ellu-fe, pull requests merged in 2025-04, with the labels that each got.

#2 feat: 프로젝트 초기셋팅(#1)
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.mjs
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.module.css
  frontend/src/app/page.tsx
  frontend/tsconfig.json
Labels: feat

#4 3 feature fe 라이브러리 설치 및 셋팅
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/(with-mainLayout)/calendar/page.tsx
  frontend/src/app/(with-mainLayout)/layout.tsx
  frontend/src/app/(with-mainLayout)/projects/[id]/page.tsx
  frontend/src/app/(with-mainLayout)/projects/page.tsx
  frontend/src/app/auth/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/mypage/page.tsx
  frontend/src/app/not-found.tsx
  frontend/src/app/page.module.css
  frontend/src/app/page.tsx
  package-lock.json
Labels: feat

#6 5 feature 온보딩 페이지 퍼블리싱
  .gitignore
  .idea/.gitignore
  README.md
  eslint.config.mjs
  frontend/README.md
  frontend/package-lock.json
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.module.css
  frontend/src/app/page.tsx
  next.config.ts
  package-lock.json
  package.json
  public/fonts/OpenSans-VariableFont_wdth,wght.ttf
  public/fonts/Oswald-VariableFont_wght.ttf
  public/images/logo.svg
  public/images/onboarding1.svg
  public/images/onboarding2.svg
  src/app/(with-mainLayout)/calendar/page.tsx
  src/app/(with-mainLayout)/layout.tsx
  src/app/(with-mainLayout)/projects/[id]/page.tsx
  src/app/(with-mainLayout)/projects/page.tsx
  src/app/auth/login/page.tsx
  src/app/auth/page.tsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/app/not-found.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/components/MainHeader.module.css
  src/components/MainHeader.tsx
  tsconfig.json
Labels: feat

#9 chore: Add code style and commit conventions (#8)
  .github/ISSUE_TEMPLATE/1-✨feature.md
  .github/ISSUE_TEMPLATE/2-🐛fix.md
  .github/ISSUE_TEMPLATE/3-♻️refactor.md
  .github/ISSUE_TEMPLATE/4-🧪 mainteance_release.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/semantic.yml
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  .idea/sonarlint/issuestore/0/3/0398ccd0f49298b10a3d76a47800d2ebecd49859
  .idea/sonarlint/issuestore/7/0/7030d0b2f71b999ff89a343de08c414af32fc93a
  .idea/sonarlint/issuestore/f/a/fa288d1472d29beccb489a676f68739ad365fc47
  .idea/sonarlint/securityhotspotstore/0/3/0398ccd0f49298b10a3d76a47800d2ebecd49859
  .idea/sonarlint/securityhotspotstore/7/0/7030d0b2f71b999ff89a343de08c414af32fc93a
  .idea/sonarlint/securityhotspotstore/f/a/fa288d1472d29beccb489a676f68739ad365fc47
  .idea/workspace.xml
  .releaserc.json
  commitlint.config.cjs
  frontend@0.1.0
  next
  package-lock.json
  package.json
  src/app/(with-mainLayout)/layout.tsx
  src/app/(with-mainLayout)/projects/[id]/page.tsx
Labels: chore

#11 chore: Add code style and commit conventions (#8)
  commitlint.config.cjs
Labels: fix

#13 7 feature 온보딩 로그인 회원가입 페이지 퍼블리싱
  public/images/KaKaoLogin.svg
  public/images/footerLogo.svg
  public/images/loginFast.png
  src/app/(after-loginLayout)/calendar/page.tsx
  src/app/(after-loginLayout)/layout.tsx
  src/app/(after-loginLayout)/projects/[id]/page.tsx
  src/app/(after-loginLayout)/projects/page.tsx
  src/app/(before-loginLayout)/auth/kakao/callback/page.module.css
  src/app/(before-loginLayout)/auth/kakao/callback/page.tsx
  src/app/(before-loginLayout)/auth/login/page.module.css
  src/app/(before-loginLayout)/auth/login/page.tsx
  src/app/(before-loginLayout)/auth/page.tsx
  src/app/(before-loginLayout)/auth/signup/page.module.css
  src/app/(before-loginLayout)/auth/signup/page.tsx
  src/app/(before-loginLayout)/layout.module.css
  src/app/(before-loginLayout)/layout.tsx
  src/app/(before-loginLayout)/page.module.css
  src/app/(before-loginLayout)/page.tsx
  src/app/auth/login/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/components/Loading.tsx
  src/components/MainHeader.module.css
  src/components/MainHeader.tsx
  src/components/form/SignupForm.module.css
  src/components/form/SignupForm.tsx
  src/stores/userStore.ts
Labels: feat
